### ISSUE TITLE
Error: formulae require at least a URL

### ISSUE THREAD

**Issue by MotzWanted** [context-labs/mactop#6]
I attempting to install `mactop` with `brew` on a M2 Max:
```
brew tap context-labs/mactop https://github.com/context-labs/mactop
```
```
brew install mactop
Error: formulae require at least a URL
/usr/local/Homebrew/Library/Homebrew/formula.rb:316:in `determine_active_spec'
/usr/local/Homebrew/Library/Homebrew/formula.rb:249:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:570:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:570:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:794:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:1009:in `factory'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:124:in `block in load_formula_or_cask'
/usr/local/Homebrew/Library/Homebrew/api.rb:201:in `with_no_api_env_if_needed'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:116:in `load_formula_or_cask'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:81:in `block in to_formulae_and_casks'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:79:in `each'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:79:in `flat_map'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:79:in `to_formulae_and_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:196:in `run'
/usr/local/Homebrew/Library/Homebrew/brew.rb:92:in `<main>'
Please report this issue:
  https://docs.brew.sh/Troubleshooting
```

**Comment by metaspartan** [comment]
Try the following:

`brew update`

`brew upgrade`

`brew doctor`

`brew uninstall mactop`

`brew untap context-labs/mactop`

`brew tap context-labs/mactop https://github.com/context-labs/mactop`

`brew install mactop`

I am unable to reproduce the issue on a fresh install, but maybe those commands will help you, please let me know, thanks!

**Comment by MotzWanted** [comment]
Thank you for the detailed instructions. Running `brew doctor` indeed helped resolve the issue, and I successfully set up `mactop` following the subsequent steps. Everything is working smoothly now. I appreciate your assistance!
